[package]
name = "imxrt-usb"
version = "0.1.0"
authors = ["Ian McIntyre <ianpmcintyre@gmail.com>"]
edition = "2018"

[dependencies]
bitflags = "1.2"
cortex-m = "0.7"
imxrt-ral = "0.4.1"
usb-device = "0.2"

[dependencies.__log]
package = "log"
optional = true
version = "0.4"

[workspace]
members = [
    "examples/teensy4",
]

[features]
# Signals that your i.MX RT has two USB instances. This
# affects how imxrt-usb use imxrt-ral.
#
# You must enable this feature when your dependency graph
# includes any of these imxrt-ral features:
#
# - imxrt105*
# - imxrt106*
#
# Otherwise, do not enable this feature
double-instance = []
