[package]
name = "imxrt-usbd"
version = "0.1.0"
authors = ["Ian McIntyre <ianpmcintyre@gmail.com>"]
repository = "https://github.com/imxrt-rs/imxrt-usbd"
edition = "2018"
license = "MIT OR Apache-2.0"
keywords = ["imxrt", "nxp", "embedded", "usb"]
categories = ["embedded", "no-std"]
readme = "README.md"
description = """
USB driver for NXP iMX RT processors
"""
exclude = [
    ".github/*",
    "examples/*",
    ".gitignore",
]

[dependencies]
bitflags = "1.2"
cortex-m = "0.7"
imxrt-ral = "0.4.1"
usb-device = "0.2"

[dependencies.__log]
package = "log"
optional = true
version = "0.4"

[features]
# Signals that your i.MX RT has two USB instances. This
# affects how imxrt-usbd use imxrt-ral.
#
# You must enable this feature when your dependency graph
# includes any of these imxrt-ral features:
#
# - imxrt105*
# - imxrt106*
#
# Otherwise, do not enable this feature
double-instance = []

[package.metadata.docs.rs]
features = ["imxrt-ral/imxrt1062", "double-instance"]
default-target = "thumbv7em-none-eabihf"
