[package]
name = "imxrt-usb"
version = "0.1.0"
authors = ["Ian McIntyre <ianpmcintyre@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.2"
cortex-m = "0.7"
imxrt-ral = { version = "0.4.1", features = ["imxrt1062"] }  # TODO no hard-coded features
usb-device = "0.2"

[dependencies.log]
optional = true
version = "0.4"

[workspace]
members = [
    "examples/teensy4",
]